# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

#choose precise or trusty

group: edge
dist: trusty    



language: cpp

compiler:
    - gcc


env: POSTGRESQL_VERSION=9.6   PG_USER=postgres DIST=precise
      
matrix:
  include:

    - os: linux
      sudo: required
      dist: trusty
      group: edge
      env: POSTGRESQL_VERSION=9.5   PG_USER=postgres DIST=trusty


    - os: linux
      sudo: required
      dist: trusty
      group: edge
      env: POSTGRESQL_VERSION=9.4   PG_USER=postgres DIST=trusty



# executed. So things have to be tested oe by one.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # For cmake
      - kubuntu-backports
      - boost-latest
    packages:
      - cmake





before_install:
  - sudo sudo apt-get install -y libboost-program-options-dev

install:
  - sudo ./ci/travis/install-postgres.sh $POSTGRESQL_VERSION $PG_USER
  - sudo ./ci/travis/install-libpqxx.sh $DIST

before_script:

  # Add our chosen PG version to the path
  - export PATH=/usr/lib/postgresql/$POSTGRESQL_VERSION/bin:$PATH

  # initialize databases
  #- createdb  -U $PG_USER ___pgr___test___


script: 
  - ./ci/travis/osm2pgrouting_build.sh

#after_script: 
  # blank

#after_success:
  # blank
